// Generated by gencpp from file ros_tutorial/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MESSAGE_ADDTWOINTS_H
#define ROS_TUTORIAL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_tutorial/AddTwoIntsRequest.h>
#include <ros_tutorial/AddTwoIntsResponse.h>


namespace ros_tutorial
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_tutorial::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "ros_tutorial/AddTwoInts";
  }

  static const char* value(const ::ros_tutorial::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_tutorial::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ros_tutorial::AddTwoInts >
template<>
struct MD5Sum< ::ros_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::ros_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tutorial::AddTwoIntsRequest> should match
// service_traits::DataType< ::ros_tutorial::AddTwoInts >
template<>
struct DataType< ::ros_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::ros_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_tutorial::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ros_tutorial::AddTwoInts >
template<>
struct MD5Sum< ::ros_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::ros_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tutorial::AddTwoIntsResponse> should match
// service_traits::DataType< ::ros_tutorial::AddTwoInts >
template<>
struct DataType< ::ros_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::ros_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TUTORIAL_MESSAGE_ADDTWOINTS_H
