// Generated by gencpp from file ros_tutorial/RobotStatus.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MESSAGE_ROBOTSTATUS_H
#define ROS_TUTORIAL_MESSAGE_ROBOTSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorial
{
template <class ContainerAllocator>
struct RobotStatus_
{
  typedef RobotStatus_<ContainerAllocator> Type;

  RobotStatus_()
    : robot_id()
    , battery(0.0)
    , is_loaded(false)  {
    }
  RobotStatus_(const ContainerAllocator& _alloc)
    : robot_id(_alloc)
    , battery(0.0)
    , is_loaded(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_id_type;
  _robot_id_type robot_id;

   typedef float _battery_type;
  _battery_type battery;

   typedef uint8_t _is_loaded_type;
  _is_loaded_type is_loaded;





  typedef boost::shared_ptr< ::ros_tutorial::RobotStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorial::RobotStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatus_

typedef ::ros_tutorial::RobotStatus_<std::allocator<void> > RobotStatus;

typedef boost::shared_ptr< ::ros_tutorial::RobotStatus > RobotStatusPtr;
typedef boost::shared_ptr< ::ros_tutorial::RobotStatus const> RobotStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorial::RobotStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorial::RobotStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tutorial::RobotStatus_<ContainerAllocator1> & lhs, const ::ros_tutorial::RobotStatus_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id &&
    lhs.battery == rhs.battery &&
    lhs.is_loaded == rhs.is_loaded;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tutorial::RobotStatus_<ContainerAllocator1> & lhs, const ::ros_tutorial::RobotStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorial::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85a94cf16a4b07901025c9058def70e5";
  }

  static const char* value(const ::ros_tutorial::RobotStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85a94cf16a4b0790ULL;
  static const uint64_t static_value2 = 0x1025c9058def70e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorial::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorial/RobotStatus";
  }

  static const char* value(const ::ros_tutorial::RobotStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorial::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot_id\n"
"float32 battery\n"
"bool is_loaded\n"
;
  }

  static const char* value(const ::ros_tutorial::RobotStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorial::RobotStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.battery);
      stream.next(m.is_loaded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorial::RobotStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorial::RobotStatus_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_id);
    s << indent << "battery: ";
    Printer<float>::stream(s, indent + "  ", v.battery);
    s << indent << "is_loaded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_loaded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIAL_MESSAGE_ROBOTSTATUS_H
